server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/v1/users/**
            - id: vehicle-service
              uri: lb://VEHICLE-SERVICE
              predicates:
                - Path=/api/v1/vehicles/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/